### ISSUE TITLE
Issue with ToolsManager Import in deepset/conversational-agent Example

### ISSUE THREAD

**Issue by sybernomad** [deepset-ai/prompthub#52]
**Description**:
I encountered an issue while referencing the `deepset/conversational-agent` example. It appears that the `ToolsManager` from the `haystack.agents` module is not importable.

The problematic code can be observed in this section: 
[Link to deepset-ai/prompthub](https://github.com/deepset-ai/prompthub/blob/1814e1f1af1e6b0240abfc5e6c48510e46c12753/prompts/deepset-conversational-agent.md?plain=1#L15)

**Reproduction Steps**:
Attempting the import produces the following error:
```python
>>> from haystack.agents import ToolsManager
/workspaces/testapp/.venv/lib/python3.8/site-packages/quantulum3/classifier.py:12: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  import pkg_resources
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'ToolsManager' from 'haystack.agents' (/workspaces/testapp/.venv/lib/python3.8/site-packages/haystack/agents/__init__.py)
```

**Installed Dependencies**:
For reference, below are the relevant dependencies I have installed in my environment:
```toml
[tool.poetry.dependencies]
python = "^3.8"
farm-haystack = {extras = ["inference", "preprocessing", "weaviate", "collab"], version = "^1.20.1"}
```

I appreciate any guidance or solutions to this issue.

**Comment by bilgeyucel** [comment]
Hi @sybernomad, thank you for reporting this! The import statement should be `from haystack.agents.base import ToolsManager` instead. I'll fix it now :)
